<?php
/**
 * eClass - Verify Ledger Document
 * Verifies document authenticity via QR code
 */
$pageTitle = 'Verify Document';
require_once dirname(__DIR__) . '/config/app.php';

$docNumber = $_GET['doc'] ?? '';

$document = null;
$fund = null;
$period = null;

if ($docNumber) {
    $stmt = $pdo->prepare("
        SELECT ld.*, f.fund_name, f.amount, a.full_name as generated_by_name
        FROM fund_ledger_documents ld
        JOIN funds f ON ld.fund_id = f.id
        LEFT JOIN accounts a ON ld.generated_by = a.id
        WHERE ld.document_number = ?
    ");
    $stmt->execute([$docNumber]);
    $document = $stmt->fetch();

    if ($document && $document['billing_period_id']) {
        $pStmt = $pdo->prepare("SELECT * FROM fund_billing_periods WHERE id = ?");
        $pStmt->execute([$document['billing_period_id']]);
        $period = $pStmt->fetch();
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $pageTitle ?> - OneMAWD</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
</head>
<body class="bg-gray-100 min-h-screen flex items-center justify-center p-4">
    <div class="bg-white rounded-2xl shadow-xl max-w-md w-full overflow-hidden">
        <?php if ($document): ?>
        <!-- Valid Document -->
        <div class="bg-emerald-500 text-white p-6 text-center">
            <i class="fas fa-check-circle text-5xl mb-3"></i>
            <h1 class="text-xl font-bold">Document Verified</h1>
            <p class="text-emerald-100 text-sm mt-1">This is an authentic document</p>
        </div>
        <div class="p-6 space-y-4">
            <div class="text-center pb-4 border-b">
                <p class="text-xs text-gray-400 uppercase tracking-wider">Document Number</p>
                <p class="text-lg font-mono font-bold"><?= sanitize($document['document_number']) ?></p>
            </div>
            <div class="grid grid-cols-2 gap-4 text-sm">
                <div>
                    <p class="text-gray-400 text-xs">Fund Name</p>
                    <p class="font-medium"><?= sanitize($document['fund_name']) ?></p>
                </div>
                <div>
                    <p class="text-gray-400 text-xs">Amount per Student</p>
                    <p class="font-medium">₱<?= number_format($document['amount'], 2) ?></p>
                </div>
                <div>
                    <p class="text-gray-400 text-xs">Period</p>
                    <p class="font-medium"><?= $period ? sanitize($period['period_label']) : date('F Y', strtotime($document['period_start'])) ?></p>
                </div>
                <div>
                    <p class="text-gray-400 text-xs">Generated On</p>
                    <p class="font-medium"><?= date('M d, Y', strtotime($document['generated_at'])) ?></p>
                </div>
            </div>
            <div class="pt-4 border-t text-center text-xs text-gray-400">
                <p>Generated by: <?= sanitize($document['generated_by_name'] ?? 'System') ?></p>
                <p class="mt-1">OneMAWD Classroom Management System</p>
            </div>
        </div>
        <?php else: ?>
        <!-- Invalid Document -->
        <div class="bg-red-500 text-white p-6 text-center">
            <i class="fas fa-times-circle text-5xl mb-3"></i>
            <h1 class="text-xl font-bold">Document Not Found</h1>
            <p class="text-red-100 text-sm mt-1">This document could not be verified</p>
        </div>
        <div class="p-6 text-center">
            <p class="text-gray-600 text-sm mb-4">
                The document number provided does not exist in our records. 
                This may be a counterfeit or invalid document.
            </p>
            <?php if ($docNumber): ?>
            <p class="text-xs text-gray-400 font-mono">Searched: <?= sanitize($docNumber) ?></p>
            <?php endif; ?>
        </div>
        <?php endif; ?>
        <div class="bg-gray-50 px-6 py-4 text-center">
            <a href="<?= BASE_URL ?>/" class="text-sm text-blue-600 hover:text-blue-800">
                <i class="fas fa-home mr-1"></i> Go to OneMAWD
            </a>
        </div>
    </div>
</body>
</html>
